# Generated by Django 5.0.4 on 2024-05-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealership", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("truck", "Truck"),
                    ("coupe", "Coupe"),
                    ("convertible", "Convertible"),
                    ("hatchback", "Hatchback"),
                    ("minivan", "Minivan"),
                ],
                default="sedan",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="engine_size",
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("petrol", "Petrol"),
                    ("diesel", "Diesel"),
                    ("electric", "Electric"),
                    ("hybrid", "Hybrid"),
                ],
                default="petrol",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                default="manual",
                max_length=50,
            ),
        ),
    ]
