# Generated by Django 5.0.4 on 2024-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealership", "0003_car_car_type_car_engine_size_car_fuel_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="fuel",
            field=models.CharField(default="Gasoline", max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="gearbox",
            field=models.CharField(default="Automatic", max_length=50),
        ),
    ]
