# Generated by Django 5.0.4 on 2024-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealership", "0005_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reservations",
            field=models.ManyToManyField(
                blank=True, related_name="reservations", to="dealership.reservation"
            ),
        ),
    ]
