# Generated by Django 5.0.4 on 2024-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealership", "0006_profile_reservations"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
        migrations.AddField(
            model_name="car",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
        migrations.AddField(
            model_name="car",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
    ]
